spring.application.name=main-website-api

spring.datasource.url=jdbc:mysql://srv1344.hstgr.io:3306/u149343669_dashboard
spring.datasource.username=u149343669_mohamedAamer
spring.datasource.password=Mm1234MmM5678mM

# Enable H2 Console
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always

