@startuml
Interface BaseController {
    - subSectionRepository: SubSectionRepository
    - objectMapper: ObjectMapper
    - subSection: SubSection

    + updateSection(CardsContent cardsContent, String action)
}

class StringController {
    + updateSection(CardsContent cardsContent, String action)
}
class MultipleStringController {
    + updateSection(CardsContent cardsContent, String action)
}
LandingPageWords --|> MultipleStringController
LandingPageSection --|> StringController
ContactUsController --|> StringController
StringController --|> BaseController
MultipleStringController --|> BaseController

class CardsIMGsController {
    + updateSection(CardsContent cardsContent, String action)
}

CardsIMGsController --|> BaseController

ClientsSecitonController --|> CardsIMGsController
LandingPageBankLogosController --|> CardsIMGsController
LandingPageCardsController --|> CardsIMGsController
ServicesSectionController --|> CardsIMGsController
AboutUsController --|> CardsIMGsController

@enduml